function styles() {
	var editor = ace.edit("editor");
	var inputS = ace.edit("inputS");
	var inputD = ace.edit("inputD");
	if(document.body.className == 'ubuntu') {
		document.body.className = 'matrix';
		document.body.style.backgroundImage = 'url(images/matrix/background.jpg)';
		document.getElementById('window').style.backgroundImage = 'url(images/matrix/debugger_background.jpg)';
		document.getElementById('s_input').style.backgroundImage = 'url(images/matrix/input_background.png)';
		document.getElementById('s_dic_func').style.backgroundImage = 'url(images/matrix/dic_func_background.png)';
		document.getElementById('s_default').style.backgroundImage = 'url(images/matrix/default_background.png)';
		document.getElementById('s_output').style.backgroundImage = 'url(images/matrix/output_background.png)';
		document.getElementById('s_debug').style.backgroundImage = 'url(images/matrix/debug_background.png)';
		document.getElementById('s_debug_output').style.backgroundImage = 'url(images/matrix/debug_output_background.png)';
		document.getElementById('style').src = 'images/matrix/styles.png';
		document.getElementById('save_to_file').src = 'images/matrix/save_to_file.png';
		document.getElementById('open_from_file').src = 'images/matrix/open_from_file.png';
		document.getElementById('i_save').src = 'images/matrix/save.png';
		document.getElementById('back').src = 'images/matrix/back.png';
		document.getElementById('forth').src = 'images/matrix/forth.png';
		document.getElementById('run').src = 'images/matrix/run.png';
		document.getElementById('debug').src = 'images/matrix/debug.png';
		document.getElementById('dictionary').src = 'images/matrix/dictionary.png';
		document.getElementById('functions').src = 'images/matrix/functions.png';
		document.getElementById('go').src = 'images/matrix/go.png';
		document.getElementById('exit').src = 'images/matrix/exit.png';
		document.getElementById('matrix_s').removeAttribute('disabled');
		editor.setTheme("ace/theme/matrix");
		inputS.setTheme("ace/theme/matrix");
		inputD.setTheme("ace/theme/Dmatrix");
	} else if(document.body.className == 'matrix') {
		document.body.className = 'literature';
		document.body.style.backgroundImage = 'url(images/literature/background.jpg)';
		document.getElementById('window').style.backgroundImage = 'url(images/literature/debugger_background.jpg)';
		document.getElementById('s_input').style.backgroundImage = 'url(images/literature/input_background.png)';
		document.getElementById('s_dic_func').style.backgroundImage = 'url(images/literature/dic_func_background.png)';
		document.getElementById('s_default').style.backgroundImage = 'url(images/literature/default_background.png)';
		document.getElementById('s_output').style.backgroundImage = 'url(images/literature/output_background.png)';
		document.getElementById('s_debug').style.backgroundImage = 'url(images/literature/debug_background.png)';
		document.getElementById('s_debug_output').style.backgroundImage = 'url(images/literature/debug_output_background.png)';
		document.getElementById('style').src = 'images/literature/styles.png';
		document.getElementById('save_to_file').src = 'images/literature/save_to_file.png';
		document.getElementById('open_from_file').src = 'images/literature/open_from_file.png';
		document.getElementById('i_save').src = 'images/literature/save.png';
		document.getElementById('back').src = 'images/literature/back.png';
		document.getElementById('forth').src = 'images/literature/forth.png';
		document.getElementById('run').src = 'images/literature/run.png';
		document.getElementById('debug').src = 'images/literature/debug.png';
		document.getElementById('dictionary').src = 'images/literature/dictionary.png';
		document.getElementById('functions').src = 'images/literature/functions.png';
		document.getElementById('go').src = 'images/literature/go.png';
		document.getElementById('exit').src = 'images/literature/exit.png';
		document.getElementById('buttons_style').removeAttribute('disabled');
		document.getElementById('matrix_s').setAttribute('disabled', true);
		document.getElementById('literature_s').removeAttribute('disabled');
		editor.setTheme("ace/theme/old");
		inputS.setTheme("ace/theme/old");
		inputD.setTheme("ace/theme/Dold");
	} else if(document.body.className == 'literature') {
		document.body.className = 'nature';
		document.body.style.backgroundImage = 'url(images/nature/background.jpg)';
		document.getElementById('window').style.backgroundImage = 'url(images/nature/debugger_background.jpg)';
		document.getElementById('s_input').style.backgroundImage = 'url(images/nature/input_background.png)';
		document.getElementById('s_dic_func').style.backgroundImage = 'url(images/nature/dic_func_background.png)';
		document.getElementById('s_default').style.backgroundImage = 'url(images/nature/default_background.png)';
		document.getElementById('s_output').style.backgroundImage = 'url(images/nature/output_background.png)';
		document.getElementById('s_debug').style.backgroundImage = 'url(images/nature/debug_background.png)';
		document.getElementById('s_debug_output').style.backgroundImage = 'url(images/nature/debug_output_background.png)';
		document.getElementById('style').src = 'images/nature/styles.png';
		document.getElementById('save_to_file').src = 'images/nature/save_to_file.png';
		document.getElementById('open_from_file').src = 'images/nature/open_from_file.png';
		document.getElementById('i_save').src = 'images/nature/save.png';
		document.getElementById('back').src = 'images/nature/back.png';
		document.getElementById('forth').src = 'images/nature/forth.png';
		document.getElementById('run').src = 'images/nature/run.png';
		document.getElementById('debug').src = 'images/nature/debug.png';
		document.getElementById('dictionary').src = 'images/nature/dictionary.png';
		document.getElementById('functions').src = 'images/nature/functions.png';
		document.getElementById('go').src = 'images/nature/go.png';
		document.getElementById('exit').src = 'images/nature/exit.png';
		document.getElementById('buttons_style').setAttribute('disabled', true);
		document.getElementById('literature_s').setAttribute('disabled', true);
		document.getElementById('nature_s').removeAttribute('disabled');
		editor.setTheme("ace/theme/natural");
		inputS.setTheme("ace/theme/natural");
		inputD.setTheme("ace/theme/Dnatural");
	} else if(document.body.className == 'nature') {
		document.body.className = 'white';
		document.body.style.backgroundImage = 'url(images/white/background.jpg)';
		document.getElementById('window').style.backgroundImage = 'url(images/white/debugger_background.jpg)';
		document.getElementById('s_input').style.backgroundImage = 'url(images/white/input_background.png)';
		document.getElementById('s_dic_func').style.backgroundImage = 'url(images/white/dic_func_background.png)';
		document.getElementById('s_default').style.backgroundImage = 'url(images/white/default_background.png)';
		document.getElementById('s_output').style.backgroundImage = 'url(images/white/output_background.png)';
		document.getElementById('s_debug').style.backgroundImage = 'url(images/white/debug_background.png)';
		document.getElementById('s_debug_output').style.backgroundImage = 'url(images/white/debug_output_background.png)';
		document.getElementById('style').src = 'images/white/styles.png';
		document.getElementById('save_to_file').src = 'images/white/save_to_file.png';
		document.getElementById('open_from_file').src = 'images/white/open_from_file.png';
		document.getElementById('i_save').src = 'images/white/save.png';
		document.getElementById('back').src = 'images/white/back.png';
		document.getElementById('forth').src = 'images/white/forth.png';
		document.getElementById('run').src = 'images/white/run.png';
		document.getElementById('debug').src = 'images/white/debug.png';
		document.getElementById('dictionary').src = 'images/white/dictionary.png';
		document.getElementById('functions').src = 'images/white/functions.png';
		document.getElementById('go').src = 'images/white/go.png';
		document.getElementById('exit').src = 'images/white/exit.png';
		document.getElementById('buttons_style').removeAttribute('disabled');
		document.getElementById('nature_s').setAttribute('disabled', true);
		document.getElementById('white_s').removeAttribute('disabled');
		editor.setTheme("ace/theme/white");
		inputS.setTheme("ace/theme/white");
		inputD.setTheme("ace/theme/Dwhite");
	} else {
		document.body.className = 'ubuntu';
		document.body.style.backgroundImage = 'url(images/ubuntu/background.jpg)';
		document.getElementById('window').style.backgroundImage = 'url(images/ubuntu/debugger_background.jpg)';
		document.getElementById('s_input').style.backgroundImage = 'url(images/ubuntu/input_background.png)';
		document.getElementById('s_dic_func').style.backgroundImage = 'url(images/ubuntu/dic_func_background.png)';
		document.getElementById('s_default').style.backgroundImage = 'url(images/ubuntu/default_background.png)';
		document.getElementById('s_output').style.backgroundImage = 'url(images/ubuntu/output_background.png)';
		document.getElementById('s_debug').style.backgroundImage = 'url(images/ubuntu/debug_background.png)';
		document.getElementById('s_debug_output').style.backgroundImage = 'url(images/ubuntu/debug_output_background.png)';
		document.getElementById('style').src = 'images/ubuntu/styles.png';
		document.getElementById('save_to_file').src = 'images/ubuntu/save_to_file.png';
		document.getElementById('open_from_file').src = 'images/ubuntu/open_from_file.png';
		document.getElementById('i_save').src = 'images/ubuntu/save.png';
		document.getElementById('back').src = 'images/ubuntu/back.png';
		document.getElementById('forth').src = 'images/ubuntu/forth.png';
		document.getElementById('run').src = 'images/ubuntu/run.png';
		document.getElementById('debug').src = 'images/ubuntu/debug.png';
		document.getElementById('dictionary').src = 'images/ubuntu/dictionary.png';
		document.getElementById('functions').src = 'images/ubuntu/functions.png';
		document.getElementById('go').src = 'images/ubuntu/go.png';
		document.getElementById('exit').src = 'images/ubuntu/exit.png';
		document.getElementById('buttons_style').setAttribute('disabled', true);
		document.getElementById('white_s').setAttribute('disabled', true);
		editor.setTheme("ace/theme/ubuntu");
		inputS.setTheme("ace/theme/ubuntu");
		inputD.setTheme("ace/theme/Dubuntu");
	}
}
